import 'package:flutter/foundation.dart';

import '../core/api_exception.dart';
import '../models/card_details.dart';
import '../models/customer.dart';
import '../models/payment_details.dart';
import '../models/payment_method.dart';
import '../models/payment_result.dart';
import '../models/payment_session.dart';
import '../services/payment_service.dart';
import 'fastpay_flow_state.dart';

/// Orchestrates the end-to-end FastPay checkout flow.
class FastPayFlowController extends ChangeNotifier {
  FastPayFlowController({required PaymentService paymentService})
    : _paymentService = paymentService;

  final PaymentService _paymentService;
  FastPayFlowState _state = const FastPayFlowState.initial();

  FastPayFlowState get state => _state;

  Future<void> startCheckout({
    required double amount,
    required String currency,
    required Customer customer,
    required String merchantOrderId,
    required String callbackUrl,
    Map<String, dynamic>? metadata,
    String? redirectUrl,
    @Deprecated('Server-side checkout_url is generated by FastPay.')
    String? checkoutUrl,
  }) async {
    _updateState(
      _state.copyWith(
        stage: FastPayFlowStage.creatingSession,
        clearErrorMessage: true,
        clearResult: true,
      ),
    );

    try {
      final List<PaymentMethod> methods = await _paymentService.listMethods();
      
      final PaymentSession session = await _paymentService.createSession(
        amount: amount,
        currency: currency,
        customer: customer,
        merchantOrderId: merchantOrderId,
        callbackUrl: callbackUrl,
        metadata: metadata,
        redirectUrl: redirectUrl,
      );

      _updateState(
        _state.copyWith(
          stage: FastPayFlowStage.ready,
          session: session,
          payment: null,
          paymentMethods: methods,
          clearErrorMessage: true,
          clearResult: true,
        ),
      );
    } catch (error) {
      _fail(message: error.toString(), payment: null);
      rethrow;
    }
  }

  Future<PaymentResult> checkStatus() async {
    final PaymentDetails? payment = _state.payment;
    final PaymentSession? session = _state.session;
    final String? paymentId = payment?.paymentId ?? session?.paymentId;

    if (paymentId == null || paymentId.isEmpty) {
      return _fail(
        message: 'FastPay status check requires a payment_id.',
        payment: null,
      );
    }

    _updateState(
      _state.copyWith(
        stage: FastPayFlowStage.processing,
        clearErrorMessage: true,
      ),
    );

    try {
      final PaymentDetails refreshed = await _paymentService.getPayment(
        paymentId: paymentId,
      );

      final PaymentResult result = _buildResult(
        payment: refreshed,
        session: session,
      );

      _updateState(
        _state.copyWith(
          stage: _stageFromResult(result),
          payment: refreshed,
          result: result,
          errorMessage: result.errorMessage,
        ),
      );

      return result;
    } catch (error) {
      return _fail(message: error.toString(), payment: payment);
    }
  }

  /// Submits card details to process the payment (embedded checkout flow).
  ///
  /// This method is called after a session has been created and the user
  /// has filled in their card details via [FastPayCardForm].
  Future<PaymentResult> submitCardPayment(CardDetails card) async {
    final PaymentSession? session = _state.session;
    final String? paymentId = session?.paymentId;

    if (paymentId == null || paymentId.isEmpty) {
      return _fail(
        message: 'No active payment session. Please restart checkout.',
        payment: null,
      );
    }

    _updateState(
      _state.copyWith(
        stage: FastPayFlowStage.processing,
        clearErrorMessage: true,
      ),
    );

    try {
      // Add a slight delay to ensure the processing UI is visible to the user.
      await Future.delayed(const Duration(seconds: 2));

      // Submits the payment with the card details for direct processing.
      await _paymentService.retryPayment(
        paymentId: paymentId,
        paymentMethod: 'card',
        callbackUrl: null,
        redirectUrl: null,
        card: card,
      );

      // Now check the final payment status.
      final PaymentDetails refreshed = await _paymentService.getPayment(
        paymentId: paymentId,
      );

      final PaymentResult result = _buildResult(
        payment: refreshed,
        session: session,
      );

      _updateState(
        _state.copyWith(
          stage: _stageFromResult(result),
          payment: refreshed,
          result: result,
          errorMessage: result.errorMessage,
        ),
      );

      return result;
    } catch (error) {
      final PaymentDetails? payment = _state.payment;
      final String message = error is ApiException ? error.message : error.toString();
      return _fail(message: message, payment: payment);
    }
  }

  void prepareRetry() {
    _updateState(
      _state.copyWith(
        stage: FastPayFlowStage.ready,
        clearErrorMessage: true,
        clearResult: true,
      ),
    );
  }

  PaymentResult _buildResult({
    required PaymentDetails payment,
    required PaymentSession? session,
  }) {
    final String status = (payment.status ?? 'failed').toLowerCase();

    if (_successStatuses.contains(status)) {
      return PaymentResult(
        outcome: PaymentOutcome.success,
        status: payment.status,
        payment: payment,
        session: session,
        rawData: payment.rawData,
      );
    }

    if (_pendingStatuses.contains(status)) {
      return PaymentResult(
        outcome: PaymentOutcome.pending,
        status: payment.status,
        errorMessage: 'Payment is still pending.',
        payment: payment,
        session: session,
        rawData: payment.rawData,
      );
    }

    return PaymentResult(
      outcome: PaymentOutcome.failure,
      status: payment.status,
      errorMessage: 'Payment failed with status ${payment.status ?? 'unknown'}.',
      payment: payment,
      session: session,
      rawData: payment.rawData,
    );
  }

  FastPayFlowStage _stageFromResult(PaymentResult result) {
    switch (result.outcome) {
      case PaymentOutcome.success:
        return FastPayFlowStage.success;
      case PaymentOutcome.pending:
        return FastPayFlowStage.pending;
      case PaymentOutcome.failure:
        return FastPayFlowStage.failure;
    }
  }

  PaymentResult _fail({
    required String message,
    required PaymentDetails? payment,
  }) {
    final PaymentResult result = PaymentResult(
      outcome: PaymentOutcome.failure,
      status: payment?.status ?? 'failed',
      errorMessage: message,
      payment: payment,
      session: _state.session,
      rawData: payment?.rawData ?? const <String, dynamic>{},
    );

    _updateState(
      _state.copyWith(
        stage: FastPayFlowStage.failure,
        payment: payment,
        result: result,
        errorMessage: message,
      ),
    );

    return result;
  }

  void _updateState(FastPayFlowState value) {
    _state = value;
    notifyListeners();
  }
}

const Set<String> _successStatuses = <String>{
  'success',
  'succeeded',
  'successful',
  'paid',
  'completed',
  'approved',
  'authorized',
};

const Set<String> _pendingStatuses = <String>{
  'pending',
  'processing',
  'submitted',
  'created',
  'initiated',
  'requires_action',
};
