import 'package:flutter/material.dart';

import '../core/fastpay.dart';
import '../flow/fastpay_flow_controller.dart';
import '../flow/fastpay_flow_state.dart';
import '../models/card_details.dart';
import '../models/customer.dart';
import '../models/payment_result.dart';
import '../models/payment_session.dart';
import '../services/payment_service.dart';
import 'fastpay_card_form.dart';
import 'fastpay_checkout_theme.dart';
import 'fastpay_result_view.dart';

/// Internal checkout page used by [FastPayCheckout.show].
class FastPayCheckoutPage extends StatefulWidget {
  /// Creates a [FastPayCheckoutPage].
  const FastPayCheckoutPage({
    super.key,
    required this.amount,
    required this.currency,
    required this.customer,
    required this.merchantOrderId,
    required this.callbackUrl,
    @Deprecated('Server-side checkout_url is generated by FastPay.')
    this.checkoutUrl,
    this.metadata,
    this.redirectUrl,
    this.onOpenCheckout,
    this.paymentService,
  });

  /// Payment amount to charge.
  final double amount;

  /// ISO currency code.
  final String currency;

  /// Customer snapshot sent to FastPay.
  final Customer customer;

  /// Merchant order reference.
  final String merchantOrderId;

  /// Merchant-hosted checkout page configured on the backend request.
  final String? checkoutUrl;

  /// Merchant callback URL used by the backend.
  final String callbackUrl;

  /// Optional backend metadata.
  final Map<String, dynamic>? metadata;

  /// Optional redirect URL.
  final String? redirectUrl;

  /// Optional callback used to open the hosted checkout externally.
  final Future<void> Function(String checkoutUrl)? onOpenCheckout;

  /// Optional service override used in tests.
  final PaymentService? paymentService;

  @override
  State<FastPayCheckoutPage> createState() => _FastPayCheckoutPageState();
}

class _FastPayCheckoutPageState extends State<FastPayCheckoutPage> {
  late final FastPayFlowController _controller;

  @override
  void initState() {
    super.initState();
    _controller = FastPayFlowController(
      paymentService: widget.paymentService ?? FastPay.paymentService,
    );
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _start();
    });
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: FastPayCheckoutPalette.background,
      body: DecoratedBox(
        decoration: const BoxDecoration(
          gradient: LinearGradient(
            colors: <Color>[Color(0xFFF7F8FC), Color(0xFFEEF2FF)],
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
          ),
        ),
        child: AnimatedBuilder(
          animation: _controller,
          builder: (BuildContext context, _) {
            final ThemeData theme = Theme.of(context);
            final FastPayFlowState state = _controller.state;

            return SafeArea(
              child: SingleChildScrollView(
                padding: const EdgeInsets.fromLTRB(16, 12, 16, 24),
                child: Center(
                  child: ConstrainedBox(
                    constraints: const BoxConstraints(maxWidth: 420),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.stretch,
                      children: <Widget>[
                        _CheckoutHeader(
                          onClose: () => _close(_controller.state.result),
                        ),
                        const SizedBox(height: 20),
                        _CheckoutSummary(
                          amount: widget.amount,
                          currency: widget.currency,
                          merchantOrderId: widget.merchantOrderId,
                        ),
                        const SizedBox(height: 18),
                        if (state.stage == FastPayFlowStage.creatingSession ||
                            state.stage == FastPayFlowStage.initial)
                          const _StatusCard(
                            title: 'Creating secure session',
                            message:
                                'FastPay is preparing a secure payment session for your transaction.',
                            icon: Icons.shield_outlined,
                            showSpinner: true,
                          )
                        else if (state.stage == FastPayFlowStage.ready)
                          Container(
                            padding: const EdgeInsets.all(22),
                            decoration: fastPaySurfaceDecoration(),
                            child: FastPayCardForm(
                              amount: widget.amount,
                              currency: widget.currency,
                              enabled: true,
                              onSubmit: (CardDetails card) async {
                                await _controller.submitCardPayment(card);
                              },
                            ),
                          )
                        else if (state.stage == FastPayFlowStage.processing)
                          const _StatusCard(
                            title: 'Processing payment',
                            message:
                                'We are securely processing your card payment. Please wait a moment.',
                            icon: Icons.credit_card_rounded,
                            showSpinner: true,
                          )
                        else if (state.result != null)
                          FastPayResultView(
                            result: state.result!,
                            onDone: () => _close(state.result),
                            onRetry: state.result!.isFailure
                                ? _controller.prepareRetry
                                : null,
                            onRefreshStatus: state.result!.isPending
                                ? () async {
                                    await _controller.checkStatus();
                                  }
                                : null,
                          ),
                        if (state.errorMessage != null &&
                            state.stage == FastPayFlowStage.ready) ...<Widget>[
                          const SizedBox(height: 18),
                          _InlineNotice(message: state.errorMessage!),
                        ],
                        const SizedBox(height: 16),
                        Text(
                          'Powered by FastPay',
                          style: theme.textTheme.bodySmall?.copyWith(
                            color: FastPayCheckoutPalette.textSecondary,
                            fontWeight: FontWeight.w600,
                          ),
                          textAlign: TextAlign.center,
                        ),
                      ],
                    ),
                  ),
                ),
              ),
            );
          },
        ),
      ),
    );
  }

  Future<void> _start() async {
    try {
      await _controller.startCheckout(
        amount: widget.amount,
        currency: widget.currency,
        customer: widget.customer,
        merchantOrderId: widget.merchantOrderId,
        callbackUrl: widget.callbackUrl,
        metadata: widget.metadata,
        redirectUrl: widget.redirectUrl,
        checkoutUrl: widget.checkoutUrl,
      );
    } catch (_) {
      // The controller already captures the failure state.
    }
  }

  void _close(PaymentResult? result) {
    final PaymentResult finalResult =
        result ??
        PaymentResult(
          outcome: PaymentOutcome.failure,
          status: 'cancelled',
          errorMessage: 'Checkout was dismissed before completion.',
          session: _controller.state.session,
        );

    Navigator.of(context).pop(finalResult);
  }
}

class _CheckoutHeader extends StatelessWidget {
  const _CheckoutHeader({required this.onClose});

  final VoidCallback onClose;

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);

    return Row(
      children: <Widget>[
        Expanded(
          child: Row(
            children: <Widget>[
              Container(
                width: 48,
                height: 48,
                decoration: BoxDecoration(
                  color: FastPayCheckoutPalette.surface,
                  borderRadius: BorderRadius.circular(18),
                  border: Border.all(color: FastPayCheckoutPalette.border),
                ),
                child: const Icon(
                  Icons.lock_outline_rounded,
                  color: FastPayCheckoutPalette.primary,
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    Text(
                      'FastPay',
                      style: theme.textTheme.titleLarge?.copyWith(
                        color: FastPayCheckoutPalette.textPrimary,
                        fontWeight: FontWeight.w800,
                      ),
                    ),
                    const SizedBox(height: 2),
                    Text(
                      'Secure hosted checkout',
                      style: theme.textTheme.bodySmall?.copyWith(
                        color: FastPayCheckoutPalette.textSecondary,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
        const SizedBox(width: 12),
        _CircleIconButton(icon: Icons.close_rounded, onPressed: onClose),
      ],
    );
  }
}

class _CircleIconButton extends StatelessWidget {
  const _CircleIconButton({required this.icon, required this.onPressed});

  final IconData icon;
  final VoidCallback onPressed;

  @override
  Widget build(BuildContext context) {
    return Material(
      color: FastPayCheckoutPalette.surface,
      shape: const CircleBorder(),
      child: IconButton(
        onPressed: onPressed,
        icon: Icon(icon, color: FastPayCheckoutPalette.textPrimary),
      ),
    );
  }
}

class _HostedCheckoutPanel extends StatelessWidget {
  const _HostedCheckoutPanel({
    required this.session,
    required this.isBusy,
    required this.onOpenCheckout,
    required this.onRefreshStatus,
  });

  final PaymentSession? session;
  final bool isBusy;
  final Future<void> Function(String checkoutUrl)? onOpenCheckout;
  final Future<void> Function()? onRefreshStatus;

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: <Widget>[
        Container(
          padding: const EdgeInsets.all(22),
          decoration: fastPaySurfaceDecoration(),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: <Widget>[
              Text(
                'Hosted checkout',
                style: Theme.of(context).textTheme.titleLarge?.copyWith(
                  color: FastPayCheckoutPalette.textPrimary,
                  fontWeight: FontWeight.w800,
                ),
              ),
              const SizedBox(height: 8),
              Text(
                'Copy or open the secure checkout URL below, then return here to refresh the payment status.',
                style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                  color: FastPayCheckoutPalette.textSecondary,
                  height: 1.5,
                ),
              ),
              const SizedBox(height: 20),
              _HostedCheckoutCard(
                session: session,
                onOpenCheckout: onOpenCheckout,
                onRefreshStatus: onRefreshStatus,
              ),
            ],
          ),
        ),
        if (isBusy)
          Positioned.fill(
            child: Container(
              decoration: BoxDecoration(
                color: Colors.white.withValues(alpha: 0.74),
                borderRadius: BorderRadius.circular(28),
              ),
              child: const Center(
                child: CircularProgressIndicator(
                  valueColor: AlwaysStoppedAnimation<Color>(
                    FastPayCheckoutPalette.primary,
                  ),
                ),
              ),
            ),
          ),
      ],
    );
  }
}

class _HostedCheckoutCard extends StatelessWidget {
  const _HostedCheckoutCard({
    required this.session,
    required this.onOpenCheckout,
    required this.onRefreshStatus,
  });

  final PaymentSession? session;
  final Future<void> Function(String checkoutUrl)? onOpenCheckout;
  final Future<void> Function()? onRefreshStatus;

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);
    final String? checkoutUrl = session?.checkoutUrl;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: <Widget>[
        _CheckoutDetail(label: 'Status', value: session?.status ?? 'initiated'),
        if (session?.paymentId != null)
          _CheckoutDetail(
            label: 'Payment ID',
            value: formatFastPayId(session!.paymentId!),
          ),
        if (session?.reference != null)
          _CheckoutDetail(label: 'Reference', value: session!.reference!),
        if (checkoutUrl != null) ...<Widget>[
          const SizedBox(height: 4),
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: FastPayCheckoutPalette.surfaceMuted,
              borderRadius: BorderRadius.circular(18),
            ),
            child: SelectableText(
              checkoutUrl,
              style: theme.textTheme.bodyMedium?.copyWith(
                color: FastPayCheckoutPalette.primaryDark,
                height: 1.45,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
        ],
        const SizedBox(height: 20),
        if (checkoutUrl != null && onOpenCheckout != null)
          FilledButton(
            style: FilledButton.styleFrom(
              backgroundColor: FastPayCheckoutPalette.primary,
              foregroundColor: Colors.white,
              minimumSize: const Size.fromHeight(54),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(18),
              ),
              textStyle: theme.textTheme.titleMedium?.copyWith(
                fontWeight: FontWeight.w700,
              ),
            ),
            onPressed: () async => onOpenCheckout!(checkoutUrl),
            child: const Text('Open secure checkout'),
          ),
        if (checkoutUrl != null && onOpenCheckout != null)
          const SizedBox(height: 12),
        OutlinedButton(
          style: OutlinedButton.styleFrom(
            foregroundColor: FastPayCheckoutPalette.textPrimary,
            side: const BorderSide(color: FastPayCheckoutPalette.border),
            minimumSize: const Size.fromHeight(54),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(18),
            ),
            textStyle: theme.textTheme.titleMedium?.copyWith(
              fontWeight: FontWeight.w700,
            ),
          ),
          onPressed: onRefreshStatus == null
              ? null
              : () async => onRefreshStatus!(),
          child: const Text('Check payment status'),
        ),
      ],
    );
  }
}

class _CheckoutDetail extends StatelessWidget {
  const _CheckoutDetail({required this.label, required this.value});

  final String label;
  final String value;

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);

    return Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: Row(
        children: <Widget>[
          Expanded(
            child: Text(
              label,
              style: theme.textTheme.bodyMedium?.copyWith(
                color: FastPayCheckoutPalette.textSecondary,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
          const SizedBox(width: 12),
          Flexible(
            child: Text(
              value,
              style: theme.textTheme.bodyMedium?.copyWith(
                color: FastPayCheckoutPalette.textPrimary,
                fontWeight: FontWeight.w700,
              ),
              textAlign: TextAlign.end,
            ),
          ),
        ],
      ),
    );
  }
}

class _CheckoutSummary extends StatelessWidget {
  const _CheckoutSummary({
    required this.amount,
    required this.currency,
    this.merchantOrderId,
  });

  final double amount;
  final String currency;
  final String? merchantOrderId;

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);

    return Container(
      padding: const EdgeInsets.all(22),
      decoration: fastPaySurfaceDecoration(),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Row(
            children: <Widget>[
              Container(
                width: 44,
                height: 44,
                decoration: BoxDecoration(
                  color: FastPayCheckoutPalette.primarySoft,
                  borderRadius: BorderRadius.circular(14),
                ),
                child: const Icon(
                  Icons.shopping_bag_outlined,
                  color: FastPayCheckoutPalette.primary,
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    Text(
                      'Order summary',
                      style: theme.textTheme.titleMedium?.copyWith(
                        color: FastPayCheckoutPalette.textPrimary,
                        fontWeight: FontWeight.w800,
                      ),
                    ),
                    const SizedBox(height: 2),
                    Text(
                      'Review the payment details before you continue.',
                      style: theme.textTheme.bodySmall?.copyWith(
                        color: FastPayCheckoutPalette.textSecondary,
                        height: 1.4,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
          const SizedBox(height: 20),
          _SummaryRow(
            label: 'Payment amount',
            value: formatFastPayAmount(amount, currency),
            emphasize: true,
          ),
          _SummaryRow(label: 'Flow type', value: 'Hosted link'),
          if (merchantOrderId != null)
            _SummaryRow(label: 'Order reference', value: merchantOrderId!),
        ],
      ),
    );
  }
}

class _SummaryRow extends StatelessWidget {
  const _SummaryRow({
    required this.label,
    required this.value,
    this.emphasize = false,
  });

  final String label;
  final String value;
  final bool emphasize;

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);

    return Padding(
      padding: const EdgeInsets.only(bottom: 14),
      child: Row(
        children: <Widget>[
          Expanded(
            child: Text(
              label,
              style: theme.textTheme.bodyMedium?.copyWith(
                color: FastPayCheckoutPalette.textSecondary,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
          const SizedBox(width: 16),
          Flexible(
            child: Text(
              value,
              style:
                  (emphasize
                          ? theme.textTheme.titleMedium
                          : theme.textTheme.bodyMedium)
                      ?.copyWith(
                        color: FastPayCheckoutPalette.textPrimary,
                        fontWeight: FontWeight.w800,
                      ),
              textAlign: TextAlign.end,
            ),
          ),
        ],
      ),
    );
  }
}

class _StatusCard extends StatelessWidget {
  const _StatusCard({
    required this.title,
    required this.message,
    required this.icon,
    this.showSpinner = false,
  });

  final String title;
  final String message;
  final IconData icon;
  final bool showSpinner;

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);

    return Container(
      padding: const EdgeInsets.all(28),
      decoration: fastPaySurfaceDecoration(),
      child: Column(
        children: <Widget>[
          Container(
            width: 74,
            height: 74,
            decoration: BoxDecoration(
              color: FastPayCheckoutPalette.primarySoft,
              shape: BoxShape.circle,
            ),
            child: showSpinner
                ? const Padding(
                    padding: EdgeInsets.all(18),
                    child: CircularProgressIndicator(
                      strokeWidth: 3,
                      valueColor: AlwaysStoppedAnimation<Color>(
                        FastPayCheckoutPalette.primary,
                      ),
                    ),
                  )
                : Icon(icon, size: 34, color: FastPayCheckoutPalette.primary),
          ),
          const SizedBox(height: 18),
          Text(
            title,
            style: theme.textTheme.headlineSmall?.copyWith(
              color: FastPayCheckoutPalette.textPrimary,
              fontWeight: FontWeight.w800,
            ),
            textAlign: TextAlign.center,
          ),
          const SizedBox(height: 10),
          Text(
            message,
            style: theme.textTheme.bodyMedium?.copyWith(
              color: FastPayCheckoutPalette.textSecondary,
              height: 1.55,
            ),
            textAlign: TextAlign.center,
          ),
        ],
      ),
    );
  }
}

class _InlineNotice extends StatelessWidget {
  const _InlineNotice({required this.message});

  final String message;

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);

    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
      decoration: BoxDecoration(
        color: FastPayCheckoutPalette.dangerSoft,
        borderRadius: BorderRadius.circular(18),
        border: Border.all(color: FastPayCheckoutPalette.danger),
      ),
      child: Row(
        children: <Widget>[
          const Icon(
            Icons.error_outline_rounded,
            color: FastPayCheckoutPalette.danger,
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Text(
              message,
              style: theme.textTheme.bodyMedium?.copyWith(
                color: FastPayCheckoutPalette.textPrimary,
                height: 1.45,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
