import 'package:flutter/material.dart';

import '../core/fastpay.dart';
import '../flow/fastpay_flow_controller.dart';
import '../flow/fastpay_flow_state.dart';
import '../models/card_details.dart';
import '../models/customer.dart';
import '../models/payment_method.dart';
import '../models/payment_result.dart';
import '../models/payment_session.dart';
import '../services/payment_service.dart';
import 'fastpay_card_form.dart';
import 'fastpay_checkout_theme.dart';
import 'fastpay_result_view.dart';

/// Internal checkout page used by [FastPayCheckout.show].
class FastPayCheckoutPage extends StatefulWidget {
  /// Creates a [FastPayCheckoutPage].
  const FastPayCheckoutPage({
    super.key,
    required this.amount,
    required this.currency,
    required this.customer,
    required this.merchantOrderId,
    required this.callbackUrl,
    @Deprecated('Server-side checkout_url is generated by FastPay.')
    this.checkoutUrl,
    this.metadata,
    this.redirectUrl,
    this.onOpenCheckout,
    this.paymentService,
  });

  /// Payment amount to charge.
  final double amount;

  /// ISO currency code.
  final String currency;

  /// Customer snapshot sent to FastPay.
  final Customer customer;

  /// Merchant order reference.
  final String merchantOrderId;

  /// Merchant-hosted checkout page configured on the backend request.
  final String? checkoutUrl;

  /// Merchant callback URL used by the backend.
  final String callbackUrl;

  /// Optional backend metadata.
  final Map<String, dynamic>? metadata;

  /// Optional redirect URL.
  final String? redirectUrl;

  /// Optional callback used to open the hosted checkout externally.
  final Future<void> Function(String checkoutUrl)? onOpenCheckout;

  /// Optional service override used in tests.
  final PaymentService? paymentService;

  @override
  State<FastPayCheckoutPage> createState() => _FastPayCheckoutPageState();
}

class _FastPayCheckoutPageState extends State<FastPayCheckoutPage> {
  late final FastPayFlowController _controller;

  @override
  void initState() {
    super.initState();
    _controller = FastPayFlowController(
      paymentService: widget.paymentService ?? FastPay.paymentService,
    );
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _start();
    });
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: const BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.vertical(top: Radius.circular(25)),
      ),
      child: AnimatedBuilder(
        animation: _controller,
        builder: (BuildContext context, _) {
          final ThemeData theme = Theme.of(context);
          final FastPayFlowState state = _controller.state;

          return SafeArea(
            top: false,
            child: SingleChildScrollView(
              padding: const EdgeInsets.fromLTRB(16, 24, 16, 24),
              child: Center(
                child: ConstrainedBox(
                  constraints: const BoxConstraints(maxWidth: 420),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    mainAxisSize: MainAxisSize.min,
                    children: <Widget>[
                        Center(
                          child: Container(
                            margin: const EdgeInsets.only(top: 8, bottom: 24),
                            width: 60,
                            height: 3,
                            decoration: BoxDecoration(
                              color: Colors.black87,
                              borderRadius: BorderRadius.circular(2),
                            ),
                          ),
                        ),
                        if (state.stage == FastPayFlowStage.creatingSession ||
                            state.stage == FastPayFlowStage.initial)
                          const _CustomLoadingScreen(
                            title: 'Initializing...',
                            message: 'Please wait while we set up\nyour secure checkout.',
                          )
                        else if (state.stage == FastPayFlowStage.ready)
                          Container(
                            padding: const EdgeInsets.symmetric(horizontal: 4),
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.stretch,
                              children: [
                                const SizedBox(height: 24),
                                _PaymentMethodTabs(methods: state.paymentMethods),
                                const SizedBox(height: 24),
                                FastPayCardForm(
                                  amount: widget.amount,
                                  currency: widget.currency,
                                  enabled: true,
                                  onSubmit: (CardDetails card) async {
                                    await _controller.submitCardPayment(card);
                                  },
                                ),
                              ],
                            ),
                          )
                        else if (state.stage == FastPayFlowStage.processing)
                          const _CustomLoadingScreen(
                            title: 'Processing your\npayment...',
                            message: 'Please do not close the FastPay app\nor refresh the page while we\nauthorize your transaction.',
                          )
                        else if (state.result != null)
                          FastPayResultView(
                            result: state.result!,
                            onDone: () => _close(state.result),
                            onRetry: state.result!.isFailure
                                ? _controller.prepareRetry
                                : null,
                            onRefreshStatus: state.result!.isPending
                                ? () async {
                                    await _controller.checkStatus();
                                  }
                                : null,
                          ),
                        if (state.errorMessage != null &&
                            state.stage == FastPayFlowStage.ready) ...<Widget>[
                          const SizedBox(height: 18),
                          _InlineNotice(message: state.errorMessage!),
                        ],
                        const SizedBox(height: 24),
                        Center(
                          child: Image.asset(
                            'assets/images/fastpay.png',
                            package: 'fastpay_sdk',
                            height: 28,
                          ),
                        ),
                        const SizedBox(height: 8),
                      ],
                    ),
                  ),
                ),
              ),
            );
          },
        ),
      );
    }

  Future<void> _start() async {
    try {
      await _controller.startCheckout(
        amount: widget.amount,
        currency: widget.currency,
        customer: widget.customer,
        merchantOrderId: widget.merchantOrderId,
        callbackUrl: widget.callbackUrl,
        metadata: widget.metadata,
        redirectUrl: widget.redirectUrl,
        checkoutUrl: widget.checkoutUrl,
      );
    } catch (_) {
      // The controller already captures the failure state.
    }
  }

  void _close(PaymentResult? result) {
    final PaymentResult finalResult =
        result ??
        PaymentResult(
          outcome: PaymentOutcome.failure,
          status: 'cancelled',
          errorMessage: 'Checkout was dismissed before completion.',
          session: _controller.state.session,
        );

    Navigator.of(context).pop(finalResult);
  }
}

class _PaymentMethodTabs extends StatelessWidget {
  const _PaymentMethodTabs({this.methods});

  final List<PaymentMethod>? methods;

  @override
  Widget build(BuildContext context) {
    if (methods == null || methods!.isEmpty) {
      return Row(
        children: const <Widget>[
          _MethodTab(
            icon: Icons.credit_card_rounded,
            label: 'Credit Card',
            isSelected: true,
          ),
          SizedBox(width: 10),
          _MethodTab(
            icon: Icons.account_balance_wallet_outlined,
            label: 'Wallet',
            isSelected: false,
          ),
          SizedBox(width: 10),
          _MethodTab(
            imageAsset: 'assets/images/instapay.png',
            label: 'instapay',
            isSelected: false,
          ),
        ],
      );
    }

    final List<Widget> children = [];
    for (int i = 0; i < methods!.length; i++) {
      final PaymentMethod method = methods![i];
      IconData? icon;
      String? imageAsset;

      if (method.code == 'card') {
        icon = Icons.credit_card_rounded;
      } else if (method.code == 'wallet') {
        icon = Icons.account_balance_wallet_outlined;
      } else if (method.code == 'instapay') {
        imageAsset = 'assets/images/instapay.png';
      } else {
        icon = Icons.payment_rounded;
      }

      children.add(
        _MethodTab(
          icon: icon,
          imageAsset: imageAsset,
          label: method.name ?? method.code ?? 'Unknown',
          isSelected: i == 0,
        ),
      );

      if (i < methods!.length - 1) {
        children.add(const SizedBox(width: 10));
      }
    }

    return Row(children: children);
  }
}

class _MethodTab extends StatelessWidget {
  const _MethodTab({
    this.icon,
    this.imageAsset,
    required this.label,
    required this.isSelected,
  });

  final IconData? icon;
  final String? imageAsset;
  final String label;
  final bool isSelected;

  @override
  Widget build(BuildContext context) {
    final Color borderColor =
        isSelected ? FastPayCheckoutPalette.primary : const Color(0xFFE0E0E0);
    final Color bgColor =
        isSelected ? FastPayCheckoutPalette.primarySoft : Colors.white;
    final Color fgColor =
        isSelected ? FastPayCheckoutPalette.primary : const Color(0xFF8E8E93);

    Widget iconWidget;
    if (imageAsset != null) {
      iconWidget = Image.asset(
        imageAsset!,
        package: 'fastpay_sdk',
        width: 32,
        height: 24,
      );
    } else {
      iconWidget = Icon(icon, size: 24, color: fgColor);
    }

    return Expanded(
      child: Container(
        padding: const EdgeInsets.symmetric(vertical: 14),
        decoration: BoxDecoration(
          color: bgColor,
          borderRadius: BorderRadius.circular(10),
          border: Border.all(color: borderColor, width: 1.5),
        ),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            iconWidget,
            const SizedBox(height: 6),
            Text(
              label,
              style: TextStyle(
                color: fgColor,
                fontSize: 11,
                fontWeight: isSelected ? FontWeight.w700 : FontWeight.w500,
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _CheckoutHeader extends StatelessWidget {
  const _CheckoutHeader({required this.onClose});

  final VoidCallback onClose;

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);

    return Row(
      children: <Widget>[
        Expanded(
          child: Row(
            children: <Widget>[
              Container(
                width: 48,
                height: 48,
                decoration: BoxDecoration(
                  color: FastPayCheckoutPalette.surface,
                  borderRadius: BorderRadius.circular(18),
                  border: Border.all(color: FastPayCheckoutPalette.border),
                ),
                child: const Icon(
                  Icons.lock_outline_rounded,
                  color: FastPayCheckoutPalette.primary,
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    Text(
                      'FastPay',
                      style: theme.textTheme.titleLarge?.copyWith(
                        color: FastPayCheckoutPalette.textPrimary,
                        fontWeight: FontWeight.w800,
                      ),
                    ),
                    const SizedBox(height: 2),
                    Text(
                      'Secure hosted checkout',
                      style: theme.textTheme.bodySmall?.copyWith(
                        color: FastPayCheckoutPalette.textSecondary,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
        const SizedBox(width: 12),
        _CircleIconButton(icon: Icons.close_rounded, onPressed: onClose),
      ],
    );
  }
}

class _CircleIconButton extends StatelessWidget {
  const _CircleIconButton({required this.icon, required this.onPressed});

  final IconData icon;
  final VoidCallback onPressed;

  @override
  Widget build(BuildContext context) {
    return Material(
      color: FastPayCheckoutPalette.surface,
      shape: const CircleBorder(),
      child: IconButton(
        onPressed: onPressed,
        icon: Icon(icon, color: FastPayCheckoutPalette.textPrimary),
      ),
    );
  }
}

class _HostedCheckoutPanel extends StatelessWidget {
  const _HostedCheckoutPanel({
    required this.session,
    required this.isBusy,
    required this.onOpenCheckout,
    required this.onRefreshStatus,
  });

  final PaymentSession? session;
  final bool isBusy;
  final Future<void> Function(String checkoutUrl)? onOpenCheckout;
  final Future<void> Function()? onRefreshStatus;

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: <Widget>[
        Container(
          padding: const EdgeInsets.all(22),
          decoration: fastPaySurfaceDecoration(),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: <Widget>[
              Text(
                'Hosted checkout',
                style: Theme.of(context).textTheme.titleLarge?.copyWith(
                  color: FastPayCheckoutPalette.textPrimary,
                  fontWeight: FontWeight.w800,
                ),
              ),
              const SizedBox(height: 8),
              Text(
                'Copy or open the secure checkout URL below, then return here to refresh the payment status.',
                style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                  color: FastPayCheckoutPalette.textSecondary,
                  height: 1.5,
                ),
              ),
              const SizedBox(height: 20),
              _HostedCheckoutCard(
                session: session,
                onOpenCheckout: onOpenCheckout,
                onRefreshStatus: onRefreshStatus,
              ),
            ],
          ),
        ),
        if (isBusy)
          Positioned.fill(
            child: Container(
              decoration: BoxDecoration(
                color: Colors.white.withValues(alpha: 0.74),
                borderRadius: BorderRadius.circular(28),
              ),
              child: const Center(
                child: CircularProgressIndicator(
                  valueColor: AlwaysStoppedAnimation<Color>(
                    FastPayCheckoutPalette.primary,
                  ),
                ),
              ),
            ),
          ),
      ],
    );
  }
}

class _HostedCheckoutCard extends StatelessWidget {
  const _HostedCheckoutCard({
    required this.session,
    required this.onOpenCheckout,
    required this.onRefreshStatus,
  });

  final PaymentSession? session;
  final Future<void> Function(String checkoutUrl)? onOpenCheckout;
  final Future<void> Function()? onRefreshStatus;

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);
    final String? checkoutUrl = session?.checkoutUrl;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: <Widget>[
        _CheckoutDetail(label: 'Status', value: session?.status ?? 'initiated'),
        if (session?.paymentId != null)
          _CheckoutDetail(
            label: 'Payment ID',
            value: formatFastPayId(session!.paymentId!),
          ),
        if (session?.reference != null)
          _CheckoutDetail(label: 'Reference', value: session!.reference!),
        if (checkoutUrl != null) ...<Widget>[
          const SizedBox(height: 4),
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: FastPayCheckoutPalette.surfaceMuted,
              borderRadius: BorderRadius.circular(18),
            ),
            child: SelectableText(
              checkoutUrl,
              style: theme.textTheme.bodyMedium?.copyWith(
                color: FastPayCheckoutPalette.primaryDark,
                height: 1.45,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
        ],
        const SizedBox(height: 20),
        if (checkoutUrl != null && onOpenCheckout != null)
          FilledButton(
            style: FilledButton.styleFrom(
              backgroundColor: FastPayCheckoutPalette.primary,
              foregroundColor: Colors.white,
              minimumSize: const Size.fromHeight(54),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(18),
              ),
              textStyle: theme.textTheme.titleMedium?.copyWith(
                fontWeight: FontWeight.w700,
              ),
            ),
            onPressed: () async => onOpenCheckout!(checkoutUrl),
            child: const Text('Open secure checkout'),
          ),
        if (checkoutUrl != null && onOpenCheckout != null)
          const SizedBox(height: 12),
        OutlinedButton(
          style: OutlinedButton.styleFrom(
            foregroundColor: FastPayCheckoutPalette.textPrimary,
            side: const BorderSide(color: FastPayCheckoutPalette.border),
            minimumSize: const Size.fromHeight(54),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(18),
            ),
            textStyle: theme.textTheme.titleMedium?.copyWith(
              fontWeight: FontWeight.w700,
            ),
          ),
          onPressed: onRefreshStatus == null
              ? null
              : () async => onRefreshStatus!(),
          child: const Text('Check payment status'),
        ),
      ],
    );
  }
}

class _CheckoutDetail extends StatelessWidget {
  const _CheckoutDetail({required this.label, required this.value});

  final String label;
  final String value;

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);

    return Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: Row(
        children: <Widget>[
          Expanded(
            child: Text(
              label,
              style: theme.textTheme.bodyMedium?.copyWith(
                color: FastPayCheckoutPalette.textSecondary,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
          const SizedBox(width: 12),
          Flexible(
            child: Text(
              value,
              style: theme.textTheme.bodyMedium?.copyWith(
                color: FastPayCheckoutPalette.textPrimary,
                fontWeight: FontWeight.w700,
              ),
              textAlign: TextAlign.end,
            ),
          ),
        ],
      ),
    );
  }
}

class _CheckoutSummary extends StatelessWidget {
  const _CheckoutSummary({
    required this.amount,
    required this.currency,
    this.merchantOrderId,
  });

  final double amount;
  final String currency;
  final String? merchantOrderId;

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);

    return Container(
      padding: const EdgeInsets.all(22),
      decoration: fastPaySurfaceDecoration(),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Row(
            children: <Widget>[
              Container(
                width: 44,
                height: 44,
                decoration: BoxDecoration(
                  color: FastPayCheckoutPalette.primarySoft,
                  borderRadius: BorderRadius.circular(14),
                ),
                child: const Icon(
                  Icons.shopping_bag_outlined,
                  color: FastPayCheckoutPalette.primary,
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    Text(
                      'Order summary',
                      style: theme.textTheme.titleMedium?.copyWith(
                        color: FastPayCheckoutPalette.textPrimary,
                        fontWeight: FontWeight.w800,
                      ),
                    ),
                    const SizedBox(height: 2),
                    Text(
                      'Review the payment details before you continue.',
                      style: theme.textTheme.bodySmall?.copyWith(
                        color: FastPayCheckoutPalette.textSecondary,
                        height: 1.4,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
          const SizedBox(height: 20),
          _SummaryRow(
            label: 'Payment amount',
            value: formatFastPayAmount(amount, currency),
            emphasize: true,
          ),
          _SummaryRow(label: 'Flow type', value: 'Hosted link'),
          if (merchantOrderId != null)
            _SummaryRow(label: 'Order reference', value: merchantOrderId!),
        ],
      ),
    );
  }
}

class _SummaryRow extends StatelessWidget {
  const _SummaryRow({
    required this.label,
    required this.value,
    this.emphasize = false,
  });

  final String label;
  final String value;
  final bool emphasize;

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);

    return Padding(
      padding: const EdgeInsets.only(bottom: 14),
      child: Row(
        children: <Widget>[
          Expanded(
            child: Text(
              label,
              style: theme.textTheme.bodyMedium?.copyWith(
                color: FastPayCheckoutPalette.textSecondary,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
          const SizedBox(width: 16),
          Flexible(
            child: Text(
              value,
              style:
                  (emphasize
                          ? theme.textTheme.titleMedium
                          : theme.textTheme.bodyMedium)
                      ?.copyWith(
                        color: FastPayCheckoutPalette.textPrimary,
                        fontWeight: FontWeight.w800,
                      ),
              textAlign: TextAlign.end,
            ),
          ),
        ],
      ),
    );
  }
}

class _CustomLoadingScreen extends StatelessWidget {
  const _CustomLoadingScreen({required this.title, required this.message});

  final String title;
  final String message;

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);

    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 40),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: <Widget>[
          Stack(
            alignment: Alignment.center,
            children: <Widget>[
              Container(
                width: 70,
                height: 70,
                decoration: const BoxDecoration(
                  color: FastPayCheckoutPalette.primarySoft,
                  shape: BoxShape.circle,
                ),
                child: const Icon(Icons.bolt_rounded, size: 40, color: FastPayCheckoutPalette.primary),
              ),
              const SizedBox(
                width: 86,
                height: 86,
                child: CircularProgressIndicator(
                  strokeWidth: 4,
                  valueColor: AlwaysStoppedAnimation<Color>(FastPayCheckoutPalette.primary),
                ),
              ),
            ],
          ),
          const SizedBox(height: 32),
          Text(
            title,
            style: theme.textTheme.titleLarge?.copyWith(
              color: FastPayCheckoutPalette.textPrimary,
              fontWeight: FontWeight.w800,
              fontSize: 22,
              height: 1.2,
            ),
            textAlign: TextAlign.center,
          ),
          const SizedBox(height: 12),
          Text(
            message,
            style: theme.textTheme.bodyMedium?.copyWith(
              color: FastPayCheckoutPalette.textSecondary,
              fontWeight: FontWeight.w500,
              height: 1.4,
            ),
            textAlign: TextAlign.center,
          ),
          const SizedBox(height: 60),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              const Icon(Icons.lock_outline_rounded, size: 14, color: FastPayCheckoutPalette.textSecondary),
              const SizedBox(width: 6),
              Text(
                'Secure 256-bit encrypted payment',
                style: theme.textTheme.bodySmall?.copyWith(
                  color: FastPayCheckoutPalette.textSecondary,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

class _InlineNotice extends StatelessWidget {
  const _InlineNotice({required this.message});

  final String message;

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);

    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
      decoration: BoxDecoration(
        color: FastPayCheckoutPalette.dangerSoft,
        borderRadius: BorderRadius.circular(18),
        border: Border.all(color: FastPayCheckoutPalette.danger),
      ),
      child: Row(
        children: <Widget>[
          const Icon(
            Icons.error_outline_rounded,
            color: FastPayCheckoutPalette.danger,
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Text(
              message,
              style: theme.textTheme.bodyMedium?.copyWith(
                color: FastPayCheckoutPalette.textPrimary,
                height: 1.45,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
