import 'package:flutter/material.dart';

import '../models/customer.dart';
import '../models/payment_result.dart';
import 'fastpay_checkout_page.dart';

/// Entry point used to present the built-in FastPay checkout UI.
class FastPayCheckout {
  FastPayCheckout._();

  /// Opens the FastPay checkout flow and returns a typed [PaymentResult].
  static Future<PaymentResult> show(
    BuildContext context, {
    required double amount,
    required String currency,
    required Customer customer,
    required String merchantOrderId,
    required String callbackUrl,
    @Deprecated('Server-side checkout_url is generated by FastPay.')
    String? checkoutUrl,
    Map<String, dynamic>? metadata,
    String? redirectUrl,
    Future<void> Function(String checkoutUrl)? onOpenCheckout,
  }) async {
    final PaymentResult? result = await Navigator.of(context)
        .push<PaymentResult>(
          MaterialPageRoute<PaymentResult>(
            fullscreenDialog: true,
            builder: (_) => FastPayCheckoutPage(
              amount: amount,
              currency: currency,
              customer: customer,
              merchantOrderId: merchantOrderId,
              checkoutUrl: checkoutUrl,
              callbackUrl: callbackUrl,
              metadata: metadata,
              redirectUrl: redirectUrl,
              onOpenCheckout: onOpenCheckout,
            ),
          ),
        );

    return result ??
        const PaymentResult(
          outcome: PaymentOutcome.failure,
          status: 'cancelled',
          errorMessage: 'Checkout was dismissed before completion.',
        );
  }
}
